FROM python:3.13
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./src/
RUN useradd app
USER app
CMD ["streamlit", "run", "src/streamlit_app.py", "--server.address", "0.0.0.0"]